[api]
dashboard = true

[providers.docker]
exposedByDefault = false

[entryPoints]

[entryPoints.web]
address = ":80"

[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"

[tls.options.default]
minVersion = "VersionTLS13"

[certificatesResolvers.acme.acme]
storage = "/ssl/acme.json"

[certificatesResolvers.acme.acme.dnsChallenge]
provider = "cloudflare"