version: "3.8"

networks:
  default:
    external:
      name: traefik_net

services:

  shaarli:
    image: shaarli/shaarli:latest
    ports:
      - 80
    volumes:
      - ./containerfs/tpl/material:/var/www/shaarli/tpl/material
      - ./containerfs/cache:/var/www/shaarli/cache
      - ./containerfs/data:/var/www/shaarli/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shaarli.entrypoints=websecure"
      - "traefik.http.routers.shaarli.tls.certresolver=acme"
      - "traefik.http.routers.shaarli.rule=Host(`${TRAEFIK_HOST}`)"
